Added paginator and view by tag
thinknetica-django-lab-02/py-dev-user pull request #28
Opened 2021-03-29 22:11 UTC by py-dev-user

Close #17

2021-03-30 09:23 UTC, mikhailborodin requested changes

2021-03-30 09:23 UTC, mikhailborodin commented on main/templatetags/main_filters.py
> +    if idx < 0:
2 одинаковых условия?

2021-03-30 09:23 UTC, mikhailborodin commented on main/views.py
> +class ItemListByTagView(ListView):
для просмотра отфильтрованных Item не надо создавать отдельное вью, всё должно работать через `ItemListView`

2021-03-30 13:04 UTC, py-dev-user commented on main/templatetags/main_filters.py
> +    if idx < 0:
Поправил.

2021-03-31 08:56 UTC, mikhailborodin requested changes

2021-03-31 08:56 UTC, mikhailborodin commented on main/views.py
> +            return ItemModel.objects.filter(tag=tag.id)
здесь тоже надо published=1

2021-04-01 22:10 UTC, py-dev-user commented on main/views.py
> +            return ItemModel.objects.filter(tag=tag.id)
Fixed

2021-04-02 10:35 UTC, mikhailborodin approved these changes

2021-04-02 18:16 UTC, merged